"""Search research: see what already ranks before writing, so topics are chosen on evidence.

Optional. Everything here needs a ``SERPER_API_KEY``; without one the tool layer
never registers these tools and the rest of the server is unaffected.
"""

from ghost_mcp.research.brief import (
    SHARED_TOPIC_PAGES,
    Opportunity,
    TopicCluster,
    assess_consensus,
    assess_opportunity,
    build_brief,
    classify_query,
    cluster_headings,
    format_signals,
    group_queries,
    local_pack,
    match_topics,
    organic_results,
    people_also_ask,
    related_searches,
    summarize_results,
    tokens,
)
from ghost_mcp.research.incumbents import (
    BUNDLED_PROFILES,
    DEFAULT_INCUMBENTS,
    DEFAULT_PROFILE,
    UGC_DOMAINS,
    Profile,
    active_profile_name,
    add_domains,
    all_profiles,
    create_profile,
    custom_domains,
    delete_profile,
    get_profile,
    is_ugc,
    registrable,
    remove_domains,
    resolve,
    set_active_profile,
    store_path,
)
from ghost_mcp.research.interview import INTERVIEW, Question, interview_plan
from ghost_mcp.research.pages import RankingPage, fetch_page, fetch_pages, parse_page
from ghost_mcp.research.serper import SerperClient

__all__ = [
    "BUNDLED_PROFILES",
    "INTERVIEW",
    "DEFAULT_INCUMBENTS",
    "DEFAULT_PROFILE",
    "Opportunity",
    "Profile",
    "Question",
    "SHARED_TOPIC_PAGES",
    "UGC_DOMAINS",
    "RankingPage",
    "SerperClient",
    "TopicCluster",
    "active_profile_name",
    "add_domains",
    "all_profiles",
    "assess_consensus",
    "assess_opportunity",
    "build_brief",
    "classify_query",
    "cluster_headings",
    "create_profile",
    "custom_domains",
    "delete_profile",
    "fetch_page",
    "fetch_pages",
    "format_signals",
    "get_profile",
    "group_queries",
    "interview_plan",
    "is_ugc",
    "local_pack",
    "match_topics",
    "organic_results",
    "parse_page",
    "people_also_ask",
    "registrable",
    "related_searches",
    "remove_domains",
    "resolve",
    "set_active_profile",
    "store_path",
    "summarize_results",
    "tokens",
]
